import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";

const poppinsFont = Poppins({
  weight: ['100', '400', '500', '600', '900'], // Các trọng lượng bạn muốn sử dụng
  subsets: ['latin'], // Subset bạn cần (latin, cyrillic, ...)
  variable: '--font-poppins', // Tạo biến CSS để sử dụng trong Tailwind
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
